# Generated by Django 5.0.6 on 2024-06-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotatoVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('link', models.URLField()),
                ('patent_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('characteristics', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_potatovariety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField()),
            ],
            options={
                'db_table': 'api_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_weatherdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CultivationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('results', models.TextField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potatovariety')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('conditions', models.TextField()),
                ('results', models.TextField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potatovariety')),
            ],
        ),
        migrations.CreateModel(
            name='PlantProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pests', models.CharField(max_length=255)),
                ('biological_measures', models.TextField()),
                ('application_date', models.DateField()),
                ('results', models.TextField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potatovariety')),
            ],
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.potatovariety')),
            ],
        ),
    ]
